In [2]:
#Create a null vector of size 10 but the fifth value which is 1
import numpy as np
a=np.zeros(10,dtype='int32')
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [3]:
#Create a vector with values ranging from 10 to 49.
import numpy as np
a=np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [6]:
#Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
x= np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np

arr=np.array([[1,2,0],[0,4,0]])
np.argwhere(arr==0)


array([[0, 2],
       [1, 0],
       [1, 2]], dtype=int64)

In [11]:
# Create a 10x10 array with random values and find the minimum and maximum values
import numpy as np
a=np.random.random((10,10))
print(a)

[[0.89023219 0.43563582 0.20728026 0.01612731 0.88224669 0.90258087
  0.01069925 0.80973827 0.63861184 0.83169977]
 [0.22970807 0.72325456 0.25780661 0.30513984 0.63962431 0.07455701
  0.15035623 0.98124504 0.34985321 0.04676926]
 [0.74287979 0.86514401 0.4207997  0.42490591 0.25618058 0.15624748
  0.70954988 0.16335083 0.74641822 0.56944751]
 [0.93197896 0.60296709 0.34920066 0.7548941  0.49990364 0.6234555
  0.52583296 0.2674478  0.51763382 0.28521776]
 [0.06239321 0.11535585 0.8822797  0.6561794  0.07672317 0.50538377
  0.58587052 0.87856455 0.88363981 0.37166261]
 [0.63187491 0.1380386  0.95304104 0.44251368 0.87665736 0.25452448
  0.15975847 0.08847383 0.49728183 0.04798258]
 [0.61735018 0.35942846 0.5282059  0.54772297 0.03615827 0.5869904
  0.72331445 0.92182267 0.50365295 0.99814474]
 [0.76807181 0.96817526 0.7254161  0.07552855 0.94220555 0.49254205
  0.24779865 0.76322324 0.62592849 0.75698819]
 [0.44566973 0.86843725 0.10243696 0.67085868 0.59475827 0.06513804
  0.08343772 0

In [15]:
#Create a random vector of size 30 and find the mean value
import numpy as np
a=np.random.randint(0,100,size=(30))
print(a)
np.mean(a)

[33  4 68 19 52 46 39  0 15 43 79 63 22  1 60 92 17 48 78 10 53 11 35 72
 69  9 15 47 66 51]


40.56666666666667